from ._utils import path
from ._utils import Corpus
from ._utils import CorpusGensim
from ._utils import load_json
from ._utils import save_json
from ._utils import load_binary
from ._utils import save_binary
from ._utils import get_depth_dict
from ._utils import reduce
